Skip running infection via `.laminas-ci.json`, since it can't use `phpdbg`
Fixes:

```
Error: ] Project tests must be in a passing state before running Infection.
         Infection runs the test suite in a RANDOM order. Make sure your tests
         do not have hidden dependencies.

         You can add these attributes to `phpunit.xml` to check it: <phpunit
         executionOrder="random" resolveDependencies="true" ...

         If you don't want to let Infection run tests in a random order, set the
         `executionOrder` to some value, for example <phpunit
         executionOrder="default"

         Check the executed command to identify the problem:
         '/usr/bin/phpdbg8.2' '-qrr' '/github/workspace/vendor/bin/phpunit'
         '--configuration'
         '/tmp/infection/phpunitConfiguration.initial.infection.xml'
         '--coverage-xml=/tmp/infection/coverage-xml'
         '--log-junit=/tmp/infection/junit.xml'
         PHPUnit reported an exit code of 1.
         Refer to the PHPUnit's output below:
         STDOUT:
         PHPUnit 10.5.41 by Sebastian Bergmann and contributors.

         Runtime:       PHP 8.2.24
         Configuration:
         /tmp/infection/phpunitConfiguration.initial.infection.xml
         Random Seed:   1737943321

         There was 1 PHPUnit test runner warning:

         1) No code coverage driver available

         No tests executed!
```